version: "3.8"

services:
  prometheus:
    image: prom/prometheus:main
    platform: linux/amd64
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "127.0.0.1:9090:9090"
    depends_on:
      - cadvisor
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:main-ubuntu
    platform: linux/amd64
    container_name: grafana
    user: "472:472"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .docker-storage/grafana/:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.41.0
    platform: linux/amd64
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "127.0.0.1:9080:8080"
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
